### ISSUE TITLE
how to zoom-in and zoom-out image on double tap

### ISSUE THREAD

**Issue by hussainhspl** [Luehang/react-native-image-layout#20]

**Comment by Luehang** [comment]
Hi,

Under the hood, it is using `Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`.  You can double tap or pinch in to see if the image is large enough to zoom in on your device.  You can also configure the settings with the props below.

# :books: Props

Props | Description | Type | Default
------ | ------ | ------ | ------
`maxScale` | Max zoom (view transformer). **Version \*1.17.0 update**. | `number` | `Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`

To zoom for this tiny image, set the prop `maxScale` to `> 1`.  **This will cause pixelated images because the image is small.**
