### ISSUE TITLE
when we zoom image using pinch, image gets back to its original position how to avoid it ?

### ISSUE THREAD

**Issue by hussainhspl** [Luehang/react-native-image-layout#21]

**Comment by Luehang** [comment]
Hi,

Under the hood, it is using `Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`.  You can double tap or pinch in to see if the image is large enough to zoom in on your device.  You can also configure the settings with the prop below.

# :books: Props

Props | Description | Type | Default
------ | ------ | ------ | ------
`maxScale` | Max zoom (view transformer). **Version \*1.17.0 update**. | `number` | `Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`

To zoom for this tiny image, set the prop `maxScale` to `> 1`.  **This will cause pixelated images because the image is small.**

**Comment by hussainhspl** [comment]
> Hi,
> 
> Under the hood, it is using `Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`. You can double tap or pinch in to see if the image is large enough to zoom in on your device. You can also configure the settings with the prop below.
> 
> # 📚 Props
> Props	Description	Type	Default
> `maxScale`	Max zoom (view transformer). **Version *1.17.0 update**.	`number`	`Math.max(imageWidth / viewWidth, imageHeight / viewHeight)`
> To zoom for this tiny image, set the prop `maxScale` to `> 1`. **This will cause pixelated images because the image is small.**

when setting maxScale = {5} 
it is giving warning: Failed prop type: Invalid prop `maxScale` of type `number` supplied to `ImageLayout`, expected `boolean`.

I am using latest version: 5.9.0
